version: '3.4'

services:

  pvqmanagement.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "secret"
      transport.host: "127.0.0.1"

  pvqmanagement.kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://pvqmanagement.elasticsearch:9200"
      ELASTICSEARCH_PASSWORD: "secret"
